name: main branch workflow - bubblegum theme

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - themes/bubblegum/**
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Abort if env var not found
        env:
          NETLIFY_ID: ${{ secrets.NETLIFY_SITE_ID_BLOGSTER_BUBBLEGUM }}
        if: "${{ env.NETLIFY_ID == '' }}"
        run: exit 1
      - run: yarn
      - run: yarn lint
      - run: yarn build:bubblegum
      # Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=themes/bubblegum/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_BLOGSTER_BUBBLEGUM }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_BLOGSTER }}

